# Generated by Django 2.2.6 on 2019-11-05 22:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=5)),
                ('tipo', models.CharField(max_length=255)),
                ('paciente', models.CharField(max_length=255)),
                ('medico', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=254)),
            ],
            managers=[
                ('objetos_exames', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('cfm', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=14)),
                ('especializacao', models.CharField(max_length=255)),
            ],
            managers=[
                ('objetos_medicos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('idade', models.IntegerField(default=0)),
                ('endereco', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('telefone', models.CharField(max_length=14)),
            ],
            managers=[
                ('objetos_pacientes', django.db.models.manager.Manager()),
            ],
        ),
    ]
