# Generated by Django 2.2.6 on 2019-11-27 03:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('easyexam', '0002_auto_20191003_2251'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exame',
            managers=[
                ('objetos_exames', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paciente',
            managers=[
                ('objetos_pacientes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='exame',
            name='status',
            field=models.CharField(max_length=254),
        ),
    ]
